# Generated by Django 5.0.6 on 2024-12-08 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freemeet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freemeet',
            name='student_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
