# Generated by Django 5.2 on 2025-05-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='admin_unread_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='user_unread_count',
            field=models.IntegerField(default=0),
        ),
    ]
