# Generated by Django 5.2 on 2025-05-28 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_room_first_opener_room_last_cs_join_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='first_opener',
        ),
        migrations.RemoveField(
            model_name='room',
            name='last_cs_join_time',
        ),
        migrations.RemoveField(
            model_name='room',
            name='last_user_join_time',
        ),
    ]
