# Generated by Django 5.2 on 2025-05-28 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_room_first_opener'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='first_opener',
        ),
    ]
