# Generated by Django 5.0.6 on 2024-12-13 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='A short description about the teacher.', max_length=500, null=True)),
                ('specialization', models.CharField(blank=True, help_text="The teacher's area of expertise.", max_length=100, null=True)),
                ('profile_link', models.URLField(blank=True, help_text="Link to the teacher's full profile.", null=True)),
                ('is_active_to_be_shown_in_home', models.BooleanField(default=True)),
                ('teacher', models.OneToOneField(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
