# Generated by Django 5.0.4 on 2025-02-19 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParentProfile',
        ),
    ]
