# Generated by Django 5.1.3 on 2024-12-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_teacherinfo'),
        ('courses', '0005_level_enable_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherinfo',
            name='courses',
            field=models.ManyToManyField(related_name='teachers', to='courses.course'),
        ),
    ]
