# Generated by Django 5.1.4 on 2025-01-16 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_teacherinfo_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherInfoTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('translated_bio', models.TextField(blank=True, max_length=500, null=True)),
                ('translated_specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('teacher_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='accounts.teacherinfo')),
            ],
            options={
                'unique_together': {('teacher_info', 'language')},
            },
        ),
    ]
