# Generated by Django 5.2 on 2025-05-28 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_zoomaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent'), ('admin', 'Admin'), ('cs', 'Customer Service')], default='admin', max_length=10),
        ),
    ]
