version: '3.8'

services:
  django_app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    environment:
      - DB_NAME=django_db
      - DB_USER=django_user
      - DB_PASSWORD=django_password
      - DB_HOST=db
      - DB_PORT=3306
    depends_on:
      - db
    networks:
      - django_network

  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=django_db
      - MYSQL_USER=django_user
      - MYSQL_PASSWORD=django_password
      - MYSQL_ROOT_PASSWORD=root_password
    networks:
      - django_network

  nginx:
    image: nginx:alpine
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - django_app
    networks:
      - django_network

networks:
  django_network:
    driver: bridge

volumes:
  mysql_data:
  static_volume:
  media_volume:
