# Generated by Django 5.1.7 on 2025-03-24 19:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lecture',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='lectures', to=settings.AUTH_USER_MODEL),
        ),
    ]
