# Generated by Django 5.1.7 on 2025-04-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_studygroupresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturenote',
            name='delay_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecturenote',
            name='lecture_status',
            field=models.CharField(blank=True, choices=[('completed', 'Completed Successfully'), ('student_delayed', 'Delayed by Student'), ('teacher_delayed', 'Delayed by Teacher')], default='completed', max_length=20, null=True),
        ),
    ]
