# Generated by Django 5.1.7 on 2025-03-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_lecture_is_finished_lecture_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='finished_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
