# Generated by Django 5.1.7 on 2025-04-13 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_lecturenote_delay_reason_lecturenote_lecture_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecture',
            options={'ordering': ['-live_link_date']},
        ),
    ]
