# Generated by Django 5.1.7 on 2025-03-24 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_lecture_finished_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='participants',
        ),
    ]
