# Generated by Django 5.1.7 on 2025-04-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_alter_lecture_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturenote',
            name='lecture_status',
            field=models.CharField(blank=True, choices=[('completed', 'Completed Successfully'), ('student_delayed', 'Delayed or not attendeded by Student'), ('teacher_delayed', 'Delayed or not attendeded by Teacher')], default='completed', max_length=20, null=True),
        ),
    ]
