# Generated by Django 5.1.7 on 2025-03-28 15:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_remove_lecture_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='duration',
            field=models.IntegerField(default=300, validators=[django.core.validators.MaxValueValidator(300)]),
        ),
    ]
