# Generated by Django 5.1.7 on 2025-03-28 16:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_alter_lecture_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='duration',
            field=models.IntegerField(default=60, validators=[django.core.validators.MaxValueValidator(300)]),
        ),
    ]
