# Generated by Django 5.2 on 2025-05-18 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_zoomaccount'),
        ('subscriptions', '0006_studygroup_name_alter_studygroup_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='is_owner_link',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lecture',
            name='link_valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='zoom_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temporary_links', to='accounts.zoomaccount'),
        ),
    ]
