# Generated by Django 5.1.7 on 2025-03-29 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_alter_lecture_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='is_visited',
            field=models.BooleanField(default=False),
        ),
    ]
