# Generated by Django 5.2 on 2025-05-20 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_lecturevisithistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyGroupReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_reported_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('study_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='subscriptions.studygroup')),
            ],
            options={
                'unique_together': {('study_group',)},
            },
        ),
    ]
