# Generated by Django 5.0.6 on 2024-12-14 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacheravailability',
            old_name='is_recurring',
            new_name='is_available',
        ),
    ]
