# Generated by Django 5.0.6 on 2024-12-14 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_rename_is_recurring_teacheravailability_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='day',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='teacher',
        ),
        migrations.AddField(
            model_name='appointment',
            name='avialability',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appointments.teacheravailability'),
            preserve_default=False,
        ),
    ]
