# Generated by Django 5.1.3 on 2024-12-25 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_remove_appointment_day_remove_appointment_end_time_and_more'),
        ('courses', '0004_alter_levelcontent_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacheravailability',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
