# Generated by Django 5.1.3 on 2024-12-28 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_teacheravailability_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacheravailability',
            name='course',
        ),
    ]
