# Generated by Django 5.1.3 on 2024-12-18 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_levelcontent_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelcontent',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='courses.level'),
        ),
    ]
