# Generated by Django 5.1.3 on 2024-12-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_levelcontent_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='enable_pricing',
            field=models.BooleanField(default=True),
        ),
    ]
