# Generated by Django 5.0.6 on 2024-12-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_level_enable_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='preview_video',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='level',
            name='preview_video',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='levelcontent',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='session',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='track',
            name='preview_video',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
