# Generated by Django 5.1.4 on 2025-01-16 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_name_alter_course_preview_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('translated_name', models.CharField(max_length=200)),
                ('translated_description', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='courses.course')),
            ],
            options={
                'unique_together': {('course', 'language')},
            },
        ),
        migrations.CreateModel(
            name='LevelContentTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('translated_name', models.CharField(max_length=200)),
                ('level_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='courses.levelcontent')),
            ],
            options={
                'unique_together': {('level_content', 'language')},
            },
        ),
        migrations.CreateModel(
            name='LevelTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('translated_name', models.CharField(max_length=200)),
                ('translated_description', models.TextField()),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='courses.level')),
            ],
            options={
                'unique_together': {('level', 'language')},
            },
        ),
        migrations.CreateModel(
            name='SessionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('translated_title', models.CharField(max_length=200)),
                ('translated_content', models.TextField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='courses.session')),
            ],
            options={
                'unique_together': {('session', 'language')},
            },
        ),
        migrations.CreateModel(
            name='TrackTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('translated_name', models.CharField(max_length=200)),
                ('translated_description', models.TextField()),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='courses.track')),
            ],
            options={
                'unique_together': {('track', 'language')},
            },
        ),
    ]
