# Generated by Django 5.0.4 on 2025-01-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_coursetranslation_levelcontenttranslation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='egypt_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
