# Generated by Django 5.0.4 on 2025-02-15 01:34

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('video', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(choices=[('terms', 'Terms and Conditions'), ('refund', 'Refund Policy'), ('exchange', 'Exchange Policy'), ('privacy', 'Privacy Policy')], max_length=20, unique=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyInfoTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('translated_name', models.CharField(max_length=255)),
                ('translated_description', models.TextField()),
                ('company_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='about.companyinfo')),
            ],
            options={
                'unique_together': {('company_info', 'language')},
            },
        ),
        migrations.CreateModel(
            name='PolicyTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('translated_content', ckeditor.fields.RichTextField()),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='about.policy')),
            ],
            options={
                'unique_together': {('policy', 'language')},
            },
        ),
    ]
