# Generated by Django 5.0.4 on 2025-02-09 23:56

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('video', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='FinalProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('code_url', models.CharField(blank=True, max_length=255, null=True)),
                ('preview_url', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(upload_to='final_projects/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(choices=[('terms', 'Terms and Conditions'), ('refund', 'Refund Policy'), ('exchange', 'Exchange Policy'), ('privacy', 'Privacy Policy')], max_length=20, unique=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=2)),
                ('platform_name', models.CharField(max_length=50)),
                ('icon', models.ImageField(upload_to='social_icons/')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='defaults/software.gif', upload_to='techs/')),
                ('color', models.CharField(default='blue', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FinalProjectTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('translated_title', models.CharField(max_length=255)),
                ('translated_description', models.TextField()),
                ('final_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='about.finalproject')),
            ],
        ),
        migrations.CreateModel(
            name='TechUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='about.tech')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDescriptionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('translated_title', models.CharField(max_length=255)),
                ('translated_description', models.TextField()),
                ('company_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='about.companydescription')),
            ],
            options={
                'unique_together': {('company_description', 'language')},
            },
        ),
        migrations.CreateModel(
            name='CompanyInfoTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('translated_name', models.CharField(max_length=255)),
                ('translated_description', models.TextField()),
                ('company_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='about.companyinfo')),
            ],
            options={
                'unique_together': {('company_info', 'language')},
            },
        ),
        migrations.CreateModel(
            name='PolicyTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('translated_content', ckeditor.fields.RichTextField()),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='about.policy')),
            ],
            options={
                'unique_together': {('policy', 'language')},
            },
        ),
        migrations.CreateModel(
            name='TechTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('translated_name', models.CharField(max_length=100)),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='about.tech')),
            ],
            options={
                'unique_together': {('tech', 'language')},
            },
        ),
        migrations.CreateModel(
            name='TechUsageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('translated_name', models.CharField(max_length=100)),
                ('tech_usage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='about.techusage')),
            ],
            options={
                'unique_together': {('tech_usage', 'language')},
            },
        ),
    ]
