# Generated by Django 5.0.4 on 2025-02-15 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyinfotranslation',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='policytranslation',
            options={'default_permissions': ()},
        ),
    ]
