# Generated by Django 5.0.6 on 2024-12-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_tech_companyinfo_video_techusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tech',
            name='color',
            field=models.CharField(default='blue', max_length=50),
        ),
        migrations.AddField(
            model_name='tech',
            name='image',
            field=models.ImageField(default='defaults/software.gif', upload_to='techs/'),
        ),
    ]
