# Generated by Django 5.0.4 on 2025-02-15 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_companyinfotranslation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyinfotranslation',
            options={'default_permissions': ()},
        ),
    ]
