# Generated by Django 5.2.13 on 2026-04-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_freesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontenttranslation',
            name='free_session_privacy_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontenttranslation',
            name='free_session_section_badge',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontenttranslation',
            name='free_session_section_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontenttranslation',
            name='free_session_section_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontenttranslation',
            name='hero_pricing_note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontenttranslation',
            name='hero_trust_badge_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontenttranslation',
            name='hero_trust_badge_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontenttranslation',
            name='hero_trust_badge_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontenttranslation',
            name='hero_trust_badge_4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontenttranslation',
            name='process_section_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontenttranslation',
            name='process_section_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontenttranslation',
            name='testimonials_section_subtitle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontenttranslation',
            name='testimonials_section_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepagefeaturetranslation',
            name='meta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepagefeaturetranslation',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homepagecontenttranslation',
            name='hero_badge',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homepagefeature',
            name='section',
            field=models.CharField(choices=[('primary', 'Primary Features'), ('secondary', 'Secondary Features'), ('testimonials', 'Testimonials'), ('process', 'Process Steps')], max_length=20),
        ),
    ]
