# Generated by Django 5.2.13 on 2026-04-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_homepagecontenttranslation_free_session_privacy_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontenttranslation',
            name='family_bundle_comparison_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontenttranslation',
            name='family_bundle_comparison_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontenttranslation',
            name='family_bundle_cta_button_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontenttranslation',
            name='family_bundle_cta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontenttranslation',
            name='family_bundle_cta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontenttranslation',
            name='family_bundle_faq_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontenttranslation',
            name='family_bundle_faq_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontenttranslation',
            name='family_bundle_plans_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontenttranslation',
            name='family_bundle_plans_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontenttranslation',
            name='family_bundle_section_badge',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontenttranslation',
            name='family_bundle_section_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontenttranslation',
            name='family_bundle_section_pricing_note_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontenttranslation',
            name='family_bundle_section_pricing_note_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontenttranslation',
            name='family_bundle_section_pricing_note_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontenttranslation',
            name='family_bundle_section_pricing_note_4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontenttranslation',
            name='family_bundle_section_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homepagefeature',
            name='section',
            field=models.CharField(choices=[('primary', 'Primary Features'), ('secondary', 'Secondary Features'), ('testimonials', 'Testimonials'), ('process', 'Process Steps'), ('family_bundle_plans', 'Family Bundle Plans'), ('family_bundle_comparison', 'Family Bundle Comparison'), ('family_bundle_testimonials', 'Family Bundle Testimonials'), ('family_bundle_faq', 'Family Bundle FAQ')], max_length=40),
        ),
    ]
