# Generated by Django 5.1.3 on 2024-12-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_companydescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='freemeet_phone',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
