# Generated by Django 5.2.13 on 2026-04-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_homepagecontenttranslation_family_bundle_comparison_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='video',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
