# Generated by Django 5.1.3 on 2024-12-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_companyinfo_freemeet_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Privacy Policy', max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
