# Generated by Django 5.2.13 on 2026-04-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_alter_companyinfo_email_alter_companyinfo_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='video',
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='show_company_info_phone',
            field=models.BooleanField(default=True),
        ),
    ]
