# Generated by Django 5.1.3 on 2024-12-24 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_privacycontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privacycontent',
            name='title',
        ),
    ]
