# Generated by Django 5.0.6 on 2024-12-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_remove_privacycontent_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(choices=[('terms', 'Terms and Conditions'), ('refund', 'Refund Policy'), ('exchange', 'Exchange Policy')], max_length=20, unique=True)),
                ('content', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PrivacyContent',
        ),
    ]
