# Generated by Django 5.2.13 on 2026-04-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_remove_companyinfo_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='show_company_info_phone',
            field=models.BooleanField(default=True),
        ),
    ]
