# Generated by Django 5.0.6 on 2024-12-30 21:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_policy_delete_privacycontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
