# Generated by Django 5.1.4 on 2025-01-14 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_alter_policy_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='policy_type',
            field=models.CharField(choices=[('terms', 'Terms and Conditions'), ('refund', 'Refund Policy'), ('exchange', 'Exchange Policy'), ('privacy', 'Privacy Policy')], max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='CompanyDescriptionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('translated_title', models.CharField(max_length=255)),
                ('translated_description', models.TextField()),
                ('company_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='about.companydescription')),
            ],
            options={
                'unique_together': {('company_description', 'language')},
            },
        ),
        migrations.CreateModel(
            name='CompanyInfoTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('translated_name', models.CharField(max_length=255)),
                ('translated_description', models.TextField()),
                ('company_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='about.companyinfo')),
            ],
            options={
                'unique_together': {('company_info', 'language')},
            },
        ),
        migrations.CreateModel(
            name='TechTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('translated_name', models.CharField(max_length=100)),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='about.tech')),
            ],
            options={
                'unique_together': {('tech', 'language')},
            },
        ),
        migrations.CreateModel(
            name='TechUsageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('translated_name', models.CharField(max_length=100)),
                ('tech_usage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='about.techusage')),
            ],
            options={
                'unique_together': {('tech_usage', 'language')},
            },
        ),
    ]
