# Generated by Django 5.0.4 on 2025-01-16 11:59

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_alter_policy_policy_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('translated_content', ckeditor.fields.RichTextField()),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='about.policy')),
            ],
            options={
                'unique_together': {('policy', 'language')},
            },
        ),
    ]
