# Generated by Django 5.0.4 on 2025-01-29 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0011_policytranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('code_url', models.CharField(blank=True, max_length=255, null=True)),
                ('preview_url', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(upload_to='final_projects/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinalProjectTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('translated_title', models.CharField(max_length=255)),
                ('translated_description', models.TextField()),
                ('final_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='about.finalproject')),
            ],
        ),
    ]
